# Generated by Django 5.0.6 on 2024-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("genres", models.CharField(blank=True, max_length=255, null=True)),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
