# Generated by Django 5.0.6 on 2024-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_project_app", "0003_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, default="2024-01-01", null=True),
        ),
    ]
