# Generated by Django 5.0.6 on 2024-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_project_app", "0004_alter_movie_release_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="vote_count", new_name="age",
        ),
        migrations.RemoveField(model_name="movie", name="overview",),
        migrations.RemoveField(model_name="movie", name="popularity",),
        migrations.RemoveField(model_name="movie", name="release_date",),
        migrations.RemoveField(model_name="movie", name="vote_average",),
        migrations.AddField(
            model_name="movie",
            name="gender",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="movieId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="occupation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="userId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
